version: "2"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000 #change PUID if needed
      - PGID=100  #change PGID if needed
      - TZ=America/Denver #change Time Zone if needed
    volumes:
      - /????????????/appdata/nextcloud/config:/config #/srv/dev-disk-by-label-disk1 needs to be adjusted
      - /????????????/appdata/nextcloud/data:/data     #/srv/dev-disk-by-label-disk1 needs to be adjusted
    depends_on:
      - mariadb
#    ports: # uncomment this and the next line if you want to bypass the proxy
#      - 450:443
    restart: unless-stopped
  mariadb:
    image: linuxserver/mariadb
    container_name: nextclouddb
    environment:
      - PUID=1000 #change PUID if needed
      - PGID=100  #change PGID if needed
      - MYSQL_ROOT_PASSWORD=SETPASSWORDHERE  #change password
      - TZ=America/Denver #Change Time Zone if needed
    volumes:
      - /????????????/appdata/nextclouddb:/config    #/srv/dev-disk-by-label-disk1 needs to be adjusted
    restart: unless-stopped
  swag:
    image: linuxserver/swag         #swag is the replacement for letsencrypt (see link below)
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000 #change PUID if needed
      - PGID=100  #change PGID if needed
      - TZ=America/Denver # change Time Zone if needed
      - URL=MYDOMAIN.com #insert your domain name - yourdomain.url
      - SUBDOMAINS=www,cloud
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=CLOUDFLARE@EMAIL.COM # define email; required to renew certificate
    volumes:
      - /????????????/appdata/swag:/config  #/srv/dev-disk-by-label-disk1 needs to be adjusted
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

    # Additional Changes that need to be made:
    # - - - - - -
    # Edit - \\OPENMEDIAVAULT\appdata\swag\nginx\proxy-confs\nextcloud.subdomain.conf - Make sure this file exists (remove the.conf extension)
    # Something else to edit but I can't remember. Check the log files for errors. Make sure to setup port forwarding